// dict.js
export const dict = {
  vi: { flag: "🇻🇳", total: "TỔNG", items: {} },
  
  en: {
    flag: "🇺🇸",
    total: "TOTAL",
    items: {
      "Cơm sườn + trứng": "Grilled pork chops and egg rice",
      "Cơm gà xé": "Shredded chicken rice",
      "Cơm đùi gà chiên mắm": "Fried chicken thighs with fish sauce",
      "Cơm chiên hải sản": "Seafood fried rice",
      "Cơm đùi gà xối mỡ": "Extra crispy fried chicken thighs",
      "Cơm bò xào rau củ": "Stir-fried beef with vegetables",
      "Mỳ xào bò": "Stir-fried beef noodles",
      "Mỳ xào hải sản": "Seafood fried noodles",
      "Miến xào bò": "Stir-fried beef vermicelli",
      "Miến xào hải sản": "Stir-fried seafood vermicelli",
      "Miến nước gà": "Chicken noodle soup",
      "Miến nước bò": "Beef noodle soup",
      "Miến nước hải sản": "Seafood noodle soup",
      "Cháo nghêu": "Clam porridge",
      "Cháo bò": "Beef porridge",
      "Nghêu hấp": "Steamed clams",
      "Nghêu xào": "Stir-fried clams",
      "Tôm hấp": "Steamed shrimp",
      "Tôm chiên mắm": "Fried shrimp with fish sauce",
      "Mực hấp": "Steamed squid",
      "Mực chiên mắm": "Fried squid with fish sauce",
      "Trứng thêm": "Extra egg",
      "Canh khổ qua thêm": "Extra bitter melon soup",
      "Ram chả giò (1 cái)": "Spring roll (1 pc)",
      "Sườn nướng thêm": "Extra grilled ribs",
      "Đùi gà chiên mắm thêm": "Extra fried chicken thigh with fish sauce",
      "Phần gà xé thêm": "Extra shredded chicken",
      "Đùi gà xối mỡ thêm": "Extra crispy fried chicken thigh",
      "Cơm thêm": "Extra rice",
      "Bò xào rau củ thêm": "Extra stir-fried beef with vegetables",
      "Nước ngọt các loại": "Soft drinks of all kinds",
      "Bò húc": "Red Bull",
      "Nước suối": "Spring water",
      "Nước khoáng lạt": "Mineral water",
      "Nước dừa trái": "Coconut water",
      "Nước cam tươi": "Fresh orange juice",
      "Larue": "Larue Beer",
      "Huda": "Huda Beer",
      "Saigon": "Saigon Beer",
      "Tiger": "Tiger Beer",
      "Heineken": "Heineken Beer"
    }
  },

  fr: {
    flag: "🇫🇷",
    total: "TOTAL",
    items: {
      "Cơm sườn + trứng": "Riz aux côtes de porc grillées et œuf",
      "Cơm gà xé": "Riz au poulet émincé",
      "Cơm đùi gà chiên mắm": "Riz aux cuisses de poulet au nuoc-mâm",
      "Cơm chiên hải sản": "Riz sauté aux fruits de mer",
      "Cơm đùi gà xối mỡ": "Riz à la cuisse de poulet extra croustillante",
      "Cơm bò xào rau củ": "Bœuf sauté aux légumes avec riz",
      "Mỳ xào bò": "Nouilles sautées au bœuf",
      "Mỳ xào hải sản": "Nouilles sautées aux fruits de mer",
      "Miến xào bò": "Vermicelles sautés au bœuf",
      "Miến xào hải sản": "Vermicelles sautés aux fruits de mer",
      "Miến nước gà": "Soupe de vermicelles au poulet",
      "Miến nước bò": "Soupe de vermicelles au bœuf",
      "Miến nước hải sản": "Soupe de vermicelles aux fruits de mer",
      "Cháo nghêu": "Bouillie de palourdes",
      "Cháo bò": "Bouillie de bœuf",
      "Nghêu hấp": "Palourdes à la vapeur",
      "Nghêu xào": "Palourdes sautées",
      "Tôm hấp": "Crevettes à la vapeur",
      "Tôm chiên mắm": "Crevettes frites au nuoc-mâm",
      "Mực hấp": "Calmar à la vapeur",
      "Mực chiên mắm": "Calmar frit au nuoc-mâm",
      "Trứng thêm": "Œuf supplémentaire",
      "Canh khổ qua thêm": "Soupe de margose supplémentaire",
      "Ram chả giò (1 cái)": "Pâté impérial (1 pc)",
      "Sườn nướng thêm": "Côte de porc supplémentaire",
      "Đùi gà chiên mắm thêm": "Cuisse de poulet au nuoc-mâm supplémentaire",
      "Phần gà xé thêm": "Poulet émincé supplémentaire",
      "Đùi gà xối mỡ thêm": "Cuisse de poulet croustillante supplémentaire",
      "Cơm thêm": "Riz supplémentaire",
      "Bò xào rau củ thêm": "Bœuf sauté aux légumes supplémentaire",
      "Nước ngọt các loại": "Sodas de toutes sortes",
      "Bò húc": "Red Bull",
      "Nước suối": "Eau de source",
      "Nước khoáng lạt": "Eau minérale",
      "Nước dừa trái": "Eau de coco fraîche",
      "Nước cam tươi": "Jus d'orange frais",
      "Larue": "Bière Larue",
      "Huda": "Bière Huda",
      "Saigon": "Bière Saigon",
      "Tiger": "Bière Tiger",
      "Heineken": "Bière Heineken"
    }
  },

  kr: {
    flag: "🇰🇷",
    total: "합계",
    items: {
      "Cơm sườn + trứng": "돼지갈비 구이와 계란후라이 덮밥",
      "Cơm gà xé": "닭고기 찢음 덮밥",
      "Cơm đùi gà chiên mắm": "피시 소스 닭다리 튀김 덮밥",
      "Cơm chiên hải sản": "해산물 볶음밥",
      "Cơm đùi gà xối mỡ": "바삭한 닭다리 튀김 덮밥",
      "Cơm bò xào rau củ": "소고기 야채 볶음 덮밥",
      "Mỳ xào bò": "소고기 볶음라면",
      "Mỳ xào hải sản": "해산물 볶음라면",
      "Miến xào bò": "소고기 볶음당면",
      "Miến xào hải sản": "해산물 볶음당면",
      "Miến nước gà": "닭고기 당면국수",
      "Miến nước bò": "소고기 당면국수",
      "Miến nước hải sản": "해산물 당면국수",
      "Cháo nghêu": "조개죽",
      "Cháo bò": "소고기죽",
      "Nghêu hấp": "조개 찜",
      "Nghêu xào": "조개 볶음",
      "Tôm hấp": "새우 찜",
      "Tôm chiên mắm": "피시 소스 새우 튀김",
      "Mực hấp": "오징어 찜",
      "Mực chiên mắm": "피시 소스 오징어 튀김",
      "Trứng thêm": "계란 추가",
      "Canh khổ qua thêm": "여주 국 추가",
      "Ram chả giò (1 cái)": "짜조 (1개)",
      "Sườn nướng thêm": "돼지갈비 구이 추가",
      "Đùi gà chiên mắm thêm": "피시 소스 닭다리 추가",
      "Phần gà xé thêm": "닭고기 찢음 추가",
      "Đùi gà xối mỡ thêm": "바삭한 닭다리 추가",
      "Cơm thêm": "공기밥 추가",
      "Bò xào rau củ thêm": "소고기 야채 볶음 추가",
      "Nước ngọt các loại": "탄산음료",
      "Bò húc": "레드불",
      "Nước suối": "생수",
      "Nước khoáng lạt": "미네랄 워터",
      "Nước dừa trái": "코코넛 야자수",
      "Nước cam tươi": "생오렌지 주스",
      "Larue": "라루 맥주",
      "Huda": "후다 맥주",
      "Saigon": "사이공 맥주",
      "Tiger": "타이거 맥주",
      "Heineken": "하이네켄 맥주"
    }
  },

  jp: {
    flag: "🇯🇵",
    total: "合計",
    items: {
      "Cơm sườn + trứng": "豚リブ焼きと目玉焼きご飯",
      "Cơm gà xé": "ほぐし鶏肉ご飯",
      "Cơm đùi gà chiên mắm": "鶏もも肉の ヌクマム揚げご飯",
      "Cơm chiên hải sản": "海鮮チャーハン",
      "Cơm đùi gà xối mỡ": "カリカリ鶏もも肉揚げご飯",
      "Cơm bò xào rau củ": "牛肉と野菜炒めご飯",
      "Mỳ xào bò": "牛肉炒め麺",
      "Mỳ xào hải sản": "海鮮炒め麺",
      "Miến xào bò": "牛肉炒め春雨",
      "Miến xào hải sản": "海鮮炒め春雨",
      "Miến nước gà": "鶏肉汁春雨",
      "Miến nước bò": "牛肉汁春雨",
      "Miến nước hải sản": "海鮮汁春雨",
      "Cháo nghêu": "ハマグリ粥",
      "Cháo bò": "牛肉粥",
      "Nghêu hấp": "ハマグリ蒸し",
      "Nghêu xào": "ハマグリ炒め",
      "Tôm hấp": "エビ蒸し",
      "Tôm chiên mắm": "エビのヌクマム炒め",
      "Mực hấp": "イカ蒸し",
      "Mực chiên mắm": "イカのヌクマム炒め",
      "Trứng thêm": "追加トッピング卵",
      "Canh khổ qua thêm": "追加ゴーヤスープ",
      "Ram chả giò (1 cái)": "揚げ春巻き (1個)",
      "Sườn nướng thêm": "追加豚リブ焼き",
      "Đùi gà chiên mắm thêm": "追加鶏もも肉ヌクマム揚げ",
      "Phần gà xé thêm": "追加ほぐし鶏肉",
      "Đùi gà xối mỡ thêm": "追加カリカリ鶏もも肉揚げ",
      "Cơm thêm": "追加ご飯",
      "Bò xào rau củ thêm": "追加牛肉と野菜炒め",
      "Nước ngọt các loại": "ソフトドリンク各種",
      "Bò húc": "レッドブル",
      "Nước suối": "ミネラルウォーター",
      "Nước khoáng lạt": "炭酸水",
      "Nước dừa trái": "新鮮なココナッツジュース",
      "Nước cam tươi": "生オレンジジュース",
      "Larue": "ラルービール",
      "Huda": "フダビール",
      "Saigon": "サイゴンビール",
      "Tiger": "タイガービール",
      "Heineken": "ハイネケンビール"
    }
  },

  th: {
    flag: "🇹🇭",
    total: "รวม",
    items: {
      "Cơm sườn + trứng": "ข้าวหน้าซี่โครงหมูย่างและไข่ดาว",
      "Cơm gà xé": "ข้าวหน้าไก่ฉีก",
      "Cơm đùi gà chiên mắm": "ข้าวหน้าน่องไก่ทอดซอสน้ำปลา",
      "Cơm chiên hải sản": "ข้าวผัดอาหารทะเล",
      "Cơm đùi gà xối mỡ": "ข้าวหน้าน่องไก่ทอดกรอบ",
      "Cơm bò xào rau củ": "ข้าวหน้าเนื้อผัดผัก",
      "Mỳ xào bò": "บะหมี่ผัดเนื้อ",
      "Mỳ xào hải sản": "บะหมี่ผัดอาหารทะเล",
      "Miến xào bò": "วุ้นเส้นผัดเนื้อ",
      "Miến xào hải sản": "วุ้นเส้นผัดอาหารทะเล",
      "Miến nước gà": "วุ้นเส้นน้ำซุปไก่",
      "Miến nước bò": "วุ้นเส้นน้ำซุปเนื้อ",
      "Miến nước hải sản": "วุ้นเส้นน้ำซุปอาหารทะเล",
      "Cháo nghêu": "โจ๊กหอยลาย",
      "Cháo bò": "โจ๊กเนื้อ",
      "Nghêu hấp": "หอยลายนึ่ง",
      "Nghêu xào": "หอยลายผัด",
      "Tôm hấp": "กุ้งนึ่ง",
      "Tôm chiên mắm": "กุ้งทอดซอสน้ำปลา",
      "Mực hấp": "ปลาหมึกนึ่ง",
      "Mực chiên mắm": "ปลาหมึกทอดซอสน้ำปลา",
      "Trứng thêm": "เพิ่มไข่ดาว",
      "Canh khổ qua thêm": "เพิ่มต้มจืดมะระ",
      "Ram chả giò (1 cái)": "ปอเปี๊ยะทอด (1 ชิ้น)",
      "Sườn nướng thêm": "เพิ่มซี่โครงย่าง",
      "Đùi gà chiên mắm thêm": "เพิ่มน่องไก่ทอดน้ำปลา",
      "Phần gà xé thêm": "เพิ่มไก่ฉีก",
      "Đùi gà xối mỡ thêm": "เพิ่มน่องไก่กรอบ",
      "Cơm thêm": "เพิ่มข้าว",
      "Bò xào rau củ thêm": "เพิ่มเนื้อผัดผัก",
      "Nước ngọt các loại": "น้ำอัดลมต่างๆ",
      "Bò húc": "กระทิงแดง",
      "Nước suối": "น้ำเปล่า",
      "Nước khoáng lạt": "น้ำแร่",
      "Nước dừa trái": "น้ำมะพร้าวสด",
      "Nước cam tươi": "น้ำส้มคั้นสด",
      "Larue": "เบียร์ Larue",
      "Huda": "เบียร์ Huda",
      "Saigon": "เบียร์ Saigon",
      "Tiger": "เบียร์ Tiger",
      "Heineken": "เบียร์ Heineken"
    }
  },

  it: {
    flag: "🇮🇹",
    total: "TOTALE",
    items: {
      "Cơm sườn + trứng": "Riso con costolette di maiale alla griglia e uovo",
      "Cơm gà xé": "Riso con pollo sfilacciato",
      "Cơm đùi gà chiên mắm": "Riso con cosce di pollo alla salsa di pesce",
      "Cơm chiên hải sản": "Riso fritto ai frutti di mer",
      "Cơm đùi gà xối mỡ": "Riso con coscia di pollo extra croccante",
      "Cơm bò xào rau củ": "Manzo saltato con verdure e riso",
      "Mỳ xào bò": "Spaghetti saltati con manzo",
      "Mỳ xào hải sản": "Spaghetti saltati ai frutti di mare",
      "Miến xào bò": "Vermicelli saltati con manzo",
      "Miến xào hải sản": "Vermicelli saltati ai frutti di mare",
      "Miến nước gà": "Zuppa di vermicelli con pollo",
      "Miến nước bò": "Zuppa di vermicelli con manzo",
      "Miến nước hải sản": "Zuppa di vermicelli ai frutti di mare",
      "Cháo nghêu": "Porridge di vongole",
      "Cháo bò": "Porridge di manzo",
      "Nghêu hấp": "Vongole al vapore",
      "Nghêu xào": "Vongole saltate",
      "Tôm hấp": "Gamberi al vapore",
      "Tôm chiên mắm": "Gamberi fritti alla salsa di pesce",
      "Mực hấp": "Calamari al vapore",
      "Mực chiên mắm": "Calamari fritti alla salsa di pesce",
      "Trứng thêm": "Uovo extra",
      "Canh khổ qua thêm": "Zuppa di melone amaro extra",
      "Ram chả giò (1 cái)": "Involtino primavera (1 pz)",
      "Sườn nướng thêm": "Costoletta alla griglia extra",
      "Đùi gà chiên mắm thêm": "Coscia di pollo alla salsa di pesce extra",
      "Phần gà xé thêm": "Pollo sfilacciato extra",
      "Đùi gà xối mỡ thêm": "Coscia di pollo croccante extra",
      "Cơm thêm": "Riso extra",
      "Bò xào rau củ thêm": "Manzo saltato con verdure extra",
      "Nước ngọt các loại": "Bevande analcoliche varie",
      "Bò húc": "Red Bull",
      "Nước suối": "Acqua naturale",
      "Nước khoáng lạt": "Acqua minerale",
      "Nước dừa trái": "Acqua di cocco fresca",
      "Nước cam tươi": "Spremuta d'arancia fresca",
      "Larue": "Birra Larue",
      "Huda": "Birra Huda",
      "Saigon": "Birra Saigon",
      "Tiger": "Birra Tiger",
      "Heineken": "Birra Heineken"
    }
  },

  pt: {
    flag: "🇵🇹",
    total: "TOTAL",
    items: {
      "Cơm sườn + trứng": "Arroz com costeletas de porco grelhadas e ovo",
      "Cơm gà xé": "Arroz com frango desfiado",
      "Cơm đùi gà chiên mắm": "Arroz com coxas de frango com molho de peixe",
      "Cơm chiên hải sản": "Arroz frito de frutos do mar",
      "Cơm đùi gà xối mỡ": "Arroz com coxa de frango super crocante",
      "Cơm bò xào rau củ": "Carne de vaca refogada com legumes e arroz",
      "Mỳ xào bò": "Massa salteada com carne de vaca",
      "Mỳ xào hải sản": "Massa salteada com frutos do mar",
      "Miến xào bò": "Aletria salteada com carne de vaca",
      "Miến xào hải sản": "Aletria salteada com frutos do mar",
      "Miến nước gà": "Sopa de aletria com frango",
      "Miến nước bò": "Sopa de aletria com carne de vaca",
      "Miến nước hải sản": "Sopa de aletria com frutos do mar",
      "Cháo nghêu": "Canja de amêijoas",
      "Cháo bò": "Canja de carne de vaca",
      "Nghêu hấp": "Amêijoas ao vapor",
      "Nghêu xào": "Amêijoas salteadas",
      "Tôm hấp": "Camarão ao vapor",
      "Tôm chiên mắm": "Camarão frito com molho de peixe",
      "Mực hấp": "Lula ao vapor",
      "Mực chiên mắm": "Lula frita com molho de peixe",
      "Trứng thêm": "Ovo extra",
      "Canh khổ qua thêm": "Sopa de melão amargo extra",
      "Ram chả giò (1 cái)": "Chamuça / Rolinho primavera (1 un)",
      "Sườn nướng thêm": "Costeleta grelhada extra",
      "Đùi gà chiên mắm thêm": "Coxa de frango com molho de peixe extra",
      "Phần gà xé thêm": "Frango desfiado extra",
      "Đùi gà xối mỡ thêm": "Coxa de frango crocante extra",
      "Cơm thêm": "Arroz extra",
      "Bò xào rau củ thêm": "Carne de vaca refogada com legumes extra",
      "Nước ngọt các loại": "Refrigerantes variados",
      "Bò húc": "Red Bull",
      "Nước suối": "Água mineral",
      "Nước khoáng lạt": "Água com gás",
      "Nước dừa trái": "Água de coco natural",
      "Nước cam tươi": "Sumo de laranja natural",
      "Larue": "Cerveja Larue",
      "Huda": "Cerveja Huda",
      "Saigon": "Cerveja Saigon",
      "Tiger": "Cerveja Tiger",
      "Heineken": "Cerveja Heineken"
    }
  },

  es: {
    flag: "🇪🇸",
    total: "TOTAL",
    items: {
      "Cơm sườn + trứng": "Arroz con chuletas de cerdo a la parrilla y huevo",
      "Cơm gà xé": "Arroz con pollo desmenuzado",
      "Cơm đùi gà chiên mắm": "Arroz con muslos de pollo al ritmo de salsa de pescado",
      "Cơm chiên hải sản": "Arroz frito con mariscos",
      "Cơm đùi gà xối mỡ": "Arroz con muslo de pollo extra crujiente",
      "Cơm bò xào rau củ": "Ternera salteada con verduras y arroz",
      "Mỳ xào bò": "Fideos salteados con ternera",
      "Mỳ xào hải sản": "Fideos salteados con mariscos",
      "Miến xào bò": "Fideos de celofán salteados con ternera",
      "Miến xào hải sản": "Fideos de celofán salteados con mariscos",
      "Miến nước gà": "Sopa de fideos de celofán con pollo",
      "Miến nước bò": "Sopa de fideos de celofán con ternera",
      "Miến nước hải sản": "Sopa de fideos de celofán con mariscos",
      "Cháo nghêu": "Concolón o sopa de almejas",
      "Cháo bò": "Papilla de ternera",
      "Nghêu hấp": "Almejas al vapor",
      "Nghêu xào": "Almejas salteadas",
      "Tôm hấp": "Camarones al vapor",
      "Tôm chiên mắm": "Camarones fritos con salsa de pescado",
      "Mực hấp": "Calamares al vapor",
      "Mực chiên mắm": "Calamares fritos con salsa de pescado",
      "Trứng thêm": "Huevo extra",
      "Canh khổ qua thêm": "Sopa de melón amargo extra",
      "Ram chả giò (1 cái)": "Rollito de primavera (1 ud)",
      "Sườn nướng thêm": "Chuleta a la parrilla extra",
      "Đùi gà chiên mắm thêm": "Muslo de pollo a la salsa de pescado extra",
      "Phần gà xé thêm": "Pollo desmenuzado extra",
      "Đùi gà xối mỡ thêm": "Muslo de pollo crujiente extra",
      "Cơm thêm": "Arroz extra",
      "Bò xào rau củ thêm": "Ternera salteada con verduras extra",
      "Nước ngọt các loại": "Refrescos de todo tipo",
      "Bò húc": "Red Bull",
      "Nước suối": "Agua de manantial",
      "Nước khoáng lạt": "Agua mineral",
      "Nước dừa trái": "Agua de coco fresca",
      "Nước cam tươi": "Zumo de naranja fresco",
      "Larue": "Cerveza Larue",
      "Huda": "Cerveza Huda",
      "Saigon": "Cerveza Saigon",
      "Tiger": "Cerveza Tiger",
      "Heineken": "Cerveza Heineken"
    }
  },

  cn: {
    flag: "🇨🇳",
    total: "总计",
    items: {
      "Cơm sườn + trứng": "烤猪排加煎蛋饭",
      "Cơm gà xé": "鸡丝饭",
      "Cơm đùi gà chiên mắm": "鱼露炸鸡腿饭",
      "Cơm chiên hải sản": "海鲜炒饭",
      "Cơm đùi gà xối mỡ": "脆皮炸鸡腿饭",
      "Cơm bò xào rau củ": "牛肉炒时蔬饭",
      "Mỳ xào bò": "牛肉炒面",
      "Mỳ xào hải sản": "海鲜炒面",
      "Miến xào bò": "牛肉炒冬粉",
      "Miến xào hải sản": "海鲜炒冬粉",
      "Miến nước gà": "鸡肉冬粉汤",
      "Miến nước bò": "牛肉冬粉汤",
      "Miến nước hải sản": "海鲜冬粉汤",
      "Cháo nghêu": "蛤蜊粥",
      "Cháo bò": "牛肉粥",
      "Nghêu hấp": "清蒸蛤蜊",
      "Nghêu xào": "炒蛤蜊",
      "Tôm hấp": "清蒸大虾",
      "Tôm chiên mắm": "鱼露炒大虾",
      "Mực hấp": "清蒸鱿鱼",
      "Mực chiên mắm": "鱼露炒鱿鱼",
      "Trứng thêm": "加煎蛋",
      "Canh khổ qua thêm": "加苦瓜汤",
      "Ram chả giò (1 cái)": "炸春卷 (1个)",
      "Sườn nướng thêm": "加烤猪排",
      "Đùi gà chiên mắm thêm": "加鱼露鸡腿",
      "Phần gà xé thêm": "加鸡丝",
      "Đùi gà xối mỡ thêm": "加脆皮鸡腿",
      "Cơm thêm": "加饭",
      "Bò xào rau củ thêm": "加牛肉炒时蔬",
      "Nước ngọt các loại": "各类软饮料",
      "Bò húc": "红牛",
      "Nước suối": "矿泉水",
      "Nước khoáng lạt": "苏打水",
      "Nước dừa trái": "新鲜椰子汁",
      "Nước cam tươi": "鲜榨橙汁",
      "Larue": "拉鲁啤酒",
      "Huda": "胡达啤酒",
      "Saigon": "西贡啤酒",
      "Tiger": "老虎啤酒",
      "Heineken": "喜力啤酒"
    }
  },

  de: {
    flag: "🇩🇪",
    total: "GESAMT",
    items: {
      "Cơm sườn + trứng": "Reis mit gegrillten Schweinerippchen und Ei",
      "Cơm gà xé": "Reis mit gezupftem Hähnchenfleisch",
      "Cơm đùi gà chiên mắm": "Reis mit Hähnchenschenkel in Fischsauce",
      "Cơm chiên hải sản": "Gebratener Reis mit Meeresfrüchten",
      "Cơm đùi gà xối mỡ": "Reis mit knusprig frittiertem Hähnchenschenkel",
      "Cơm bò xào rau củ": "Gebratenes Rindfleisch mit Gemüse und Reis",
      "Mỳ xào bò": "Gebratene Nudeln mit Rindfleisch",
      "Mỳ xào hải sản": "Gebratene Nudeln mit Meeresfrüchten",
      "Miến xào bò": "Gebratene Glasnudeln mit Rindfleisch",
      "Miến xào hải sản": "Gebratene Glasnudeln mit Meeresfrüchten",
      "Miến nước gà": "Glasnudelsuppe mit Hähnchen",
      "Miến nước bò": "Glasnudelsuppe mit Rindfleisch",
      "Miến nước hải sản": "Glasnudelsuppe mit Meeresfrüchten",
      "Cháo nghêu": "Muschel-Reissuppe (Congee)",
      "Cháo bò": "Rindfleisch-Reissuppe (Congee)",
      "Nghêu hấp": "Gedämpfte Muscheln",
      "Nghêu xào": "Gebratene Muscheln",
      "Tôm hấp": "Gedämpfte Garnelen",
      "Tôm chiên mắm": "Gebratene Garnelen in Fischsauce",
      "Mực hấp": "Gedämpfter Tintenfisch",
      "Mực chiên mắm": "Gebratener Tintenfisch in Fischsauce",
      "Trứng thêm": "Extra Ei",
      "Canh khổ qua thêm": "Extra Bittermelonensuppe",
      "Ram chả giò (1 cái)": "Frühlingsrolle (1 Stk)",
      "Sườn nướng thêm": "Extra gegrilltes Rippchen",
      "Đùi gà chiên mắm thêm": "Extra Hähnchenschenkel in Fischsauce",
      "Phần gà xé thêm": "Extra gezupftes Hähnchen",
      "Đùi gà xối mỡ thêm": "Extra knuspriger Hähnchenschenkel",
      "Cơm thêm": "Extra Reis",
      "Bò xào rau củ thêm": "Extra gebratenes Rindfleisch mit Gemüse",
      "Nước ngọt các loại": "Alkoholfreie Getränke aller Art",
      "Bò húc": "Red Bull",
      "Nước suối": "Stilles Wasser",
      "Nước khoáng lạt": "Mineralwasser",
      "Nước dừa trái": "Frisches Kokoswasser",
      "Nước cam tươi": "Frischer Orangensaft",
      "Larue": "Larue Bier",
      "Huda": "Huda Bier",
      "Saigon": "Saigon Bier",
      "Tiger": "Tiger Bier",
      "Heineken": "Heineken Bier"
    }
  },

  ru: {
    flag: "🇷🇺",
    total: "ИТОГО",
    items: {
      "Cơm sườn + trứng": "Рис с свиными ребрышками гриль и яйцом",
      "Cơm gà xé": "Рис с измельченной курицей",
      "Cơm đùi gà chiên mắm": "Рис с куриным бедрышком в рыбном соусе",
      "Cơm chiên hải sản": "Жареный рис с морепродуктами",
      "Cơm đùi gà xối mỡ": "Рис с хрустящим куриным бедрышком",
      "Cơm bò xào rau củ": "Жареная говядина с овощами и рисом",
      "Mỳ xào bò": "Жареная лапша с говядиной",
      "Mỳ xào hải sản": "Жареная лапша с морепродуктами",
      "Miến xào bò": "Жареная стеклянная лапша с говядиной",
      "Miến xào hải sản": "Жареная стеклянная лапша с морепродуктами",
      "Miến nước gà": "Суп со стеклянной лапшой и курицей",
      "Miến nước bò": "Суп со стеклянной лапшой и говядиной",
      "Miến nước hải sản": "Суп со стеклянной лапшой и морепродуктами",
      "Cháo nghêu": "Рисовая каша с моллюсками",
      "Cháo bò": "Рисовая каша с говядиной",
      "Nghêu hấp": "Моллюски на пару",
      "Nghêu xào": "Жареные моллюски",
      "Tôm hấp": "Креветки на пару",
      "Tôm chiên mắm": "Жареные креветки в рыбном соусе",
      "Mực hấp": "Кальмары на пару",
      "Mực chiên mắm": "Жареные кальмары в рыбном соусе",
      "Trứng thêm": "Дополнительное яйцо",
      "Canh khổ qua thêm": "Дополнительный суп из горькой дыни",
      "Ram chả giò (1 cái)": "Спринг-ролл (1 шт.)",
      "Sườn nướng thêm": "Дополнительное ребрышко гриль",
      "Đùi gà chiên mắm thêm": "Дополнительное куриное бедро в рыбном соусе",
      "Phần gà xé thêm": "Дополнительная измельченная курица",
      "Đùi gà xối mỡ thêm": "Дополнительное хрустящее куриное бедро",
      "Cơm thêm": "Дополнительный рис",
      "Bò xào rau củ thêm": "Дополнительная говядина с овощами",
      "Nước ngọt các loại": "Газированные напитки в ассортименте",
      "Bò húc": "Ред Булл",
      "Nước suối": "Родниковая вода",
      "Nước khoáng lạt": "Минеральная вода",
      "Nước dừa trái": "Свежий кокосовый сок",
      "Nước cam tươi": "Свежевыжатый апельсиновый сок",
      "Larue": "Пиво Larue",
      "Huda": "Пиво Huda",
      "Saigon": "Пиво Saigon",
      "Tiger": "Пиво Tiger",
      "Heineken": "Пиво Heineken"
    }
  },

  be: {
    flag: "🇧🇪",
    total: "TOTAAL",
    items: {
      "Cơm sườn + trứng": "Rijst met gegrilde varkensribben en ei",
      "Cơm gà xé": "Rijst met gepluisde kip",
      "Cơm đùi gà chiên mắm": "Rijst met kippenbout in vissaus",
      "Cơm chiên hải sản": "Gebakken rijst met zeevruchten",
      "Cơm đùi gà xối mỡ": "Rijst met extra krokante kippenbout",
      "Cơm bò xào rau củ": "Gebakken rundvlees met groenten en rijst",
      "Mỳ xào bò": "Gebakken bami met rundvlees",
      "Mỳ xào hải sản": "Gebakken bami met zeevruchten",
      "Miến xào bò": "Gebakken glasnoedels met rundvlees",
      "Miến xào hải sản": "Gebakken glasnoedels met zeevruchten",
      "Miến nước gà": "Glasnoedelsoep met kip",
      "Miến nước bò": "Glasnoedelsoep met rundvlees",
      "Miến nước hải sản": "Glasnoedelsoep met zeevruchten",
      "Cháo nghêu": "Rijstpap met kokkels",
      "Cháo bò": "Rijstpap met rundvlees",
      "Nghêu hấp": "Gestoomde kokkels",
      "Nghêu xào": "Gebakken kokkels",
      "Tôm hấp": "Gestoomde garnalen",
      "Tôm chiên mắm": "Gebakken garnalen in vissaus",
      "Mực hấp": "Gestoomde inktvis",
      "Mực chiên mắm": "Gebakken inktvis in vissaus",
      "Trứng thêm": "Extra ei",
      "Canh khổ qua thêm": "Extra balsempeerSoep",
      "Ram chả giò (1 cái)": "Loempia (1 stk)",
      "Sườn nướng thêm": "Extra gegrilde rib",
      "Đùi gà chiên mắm thêm": "Extra kippenbout in vissaus",
      "Phần gà xé thêm": "Extra gepluisde kip",
      "Đùi gà xối mỡ thêm": "Extra krokante kippenbout",
      "Cơm thêm": "Extra rijst",
      "Bò xào rau củ thêm": "Extra gebakken rundvlees met groenten",
      "Nước ngọt các loại": "Frisdranken allerhande",
      "Bò húc": "Red Bull",
      "Nước suối": "Bronwater",
      "Nước khoáng lạt": "Spawater / Mineraalwater",
      "Nước dừa trái": "Vers kokoswater",
      "Nước cam tươi": "Vers sinaasappelsap",
      "Larue": "Larue bier",
      "Huda": "Huda bier",
      "Saigon": "Saigon bier",
      "Tiger": "Tiger bier",
      "Heineken": "Heineken bier"
    }
  },

  hu: {
    flag: "🇭🇺",
    total: "ÖSSZESEN",
    items: {
      "Cơm sườn + trứng": "Rizs grillezett sertésbordával és tojással",
      "Cơm gà xé": "Rizs tépett csirkehússal",
      "Cơm đùi gà chiên mắm": "Rizs halशószban sült csirkecombbal",
      "Cơm chiên hải sản": "Tenger gyümölcsei sült rizs",
      "Cơm đùi gà xối mỡ": "Rizs extra ropogós sült csirkecombbal",
      "Cơm bò xào rau củ": "Marhahús zöldségekkel pirítva, rizzsel",
      "Mỳ xào bò": "Pirított tészta marhahússal",
      "Mỳ xào hải sản": "Pirított tészta tenger gyümölcseivel",
      "Miến xào bò": "Pirított üvegtészta marhahússal",
      "Miến xào hải sản": "Pirított üvegtészta tenger gyümölcseivel",
      "Miến nước gà": "Üvegtészta leves csirkehússal",
      "Miến nước bò": "Üvegtészta leves marhahússal",
      "Miến nước hải sản": "Üvegtészta leves tenger gyümölcseivel",
      "Cháo nghêu": "Kagylós rizs kása",
      "Cháo bò": "Marhahúsos rizs kása",
      "Nghêu hấp": "Gőzölt kagyló",
      "Nghêu xào": "Pirított kagyló",
      "Tôm hấp": "Gőzölt rák",
      "Tôm chiên mắm": "Halशószban sült rák",
      "Mực hấp": "Gőzölt tintahal",
      "Mực chiên mắm": "Halशószban sült tintahal",
      "Trứng thêm": "Plusz tojás",
      "Canh khổ qua thêm": "Plusz keserűdinnye leves",
      "Ram chả giò (1 cái)": "Tavaszi tekercs (1 db)",
      "Sườn nướng thêm": "Plusz grillezett borda",
      "Đùi gà chiên mắm thêm": "Plusz halशószos csirkecomb",
      "Phần gà xé thêm": "Plusz tépett csirke",
      "Đùi gà xối mỡ thêm": "Plusz ropogós csirkecomb",
      "Cơm thêm": "Plusz rizs",
      "Bò xào rau củ thêm": "Plusz marhahús zöldségekkel",
      "Nước ngọt các loại": "Mindenféle üdítőital",
      "Bò húc": "Red Bull",
      "Nước suối": "Forrásvíz",
      "Nước khoáng lạt": "Ásványvíz",
      "Nước dừa trái": "Friss kókuszvíz",
      "Nước cam tươi": "Friss narancslé",
      "Larue": "Larue sör",
      "Huda": "Huda sör",
      "Saigon": "Saigon sör",
      "Tiger": "Tiger sör",
      "Heineken": "Heineken sör"
    }
  },

  at: {
    flag: "🇦🇹",
    total: "GESAMT",
    items: {
      "Cơm sườn + trứng": "Reis mit gegrillten Koteletts und Ei",
      "Cơm gà xé": "Reis mit zerfetztem Huhn",
      "Cơm đùi gà chiên mắm": "Reis mit Hühnerkeule in Fischsauce",
      "Cơm chiên hải sản": "Gebratener Reis mit Meeresfrüchten",
      "Cơm đùi gà xối mỡ": "Reis mit knuspriger Hühnerkeule",
      "Cơm bò xào rau củ": "Rindfleisch mit Gemüse und Reis",
      "Mỳ xào bò": "Gebratene Nudeln mit Rind",
      "Mỳ xào hải sản": "Gebratene Nudeln mit Meeresfrüchten",
      "Miến xào bò": "Gebratene Glasnudeln mit Rind",
      "Miến xào hải sản": "Gebratene Glasnudeln mit Meeresfrüchten",
      "Miến nước gà": "Glasnudelsuppe mit Hühnerfleisch",
      "Miến nước bò": "Glasnudelsuppe mit Rindfleisch",
      "Miến nước hải sản": "Glasnudelsuppe mit Meeresfrüchten",
      "Cháo nghêu": "Reiscongee mit Muscheln",
      "Cháo bò": "Reiscongee mit Rindfleisch",
      "Nghêu hấp": "Gedämpfte Muscheln",
      "Nghêu xào": "Gebratene Muscheln",
      "Tôm hấp": "Gedämpfte Garnelen",
      "Tôm chiên mắm": "Garnelen in Fischsauce gebraten",
      "Mực hấp": "Gedämpfter Tintenfisch",
      "Mực chiên mắm": "Tintenfisch in Fischsauce gebraten",
      "Trứng thêm": "Zusätzliches Ei",
      "Canh khổ qua thêm": "Zusätzliche Bittermelonensuppe",
      "Ram chả giò (1 cái)": "Frühlingsrolle (1 Stück)",
      "Sườn nướng thêm": "Zusätzliches gegrilltes Kotelett",
      "Đùi gà chiên mắm thêm": "Zusätzliche Hühnerkeule in Fischsauce",
      "Phần gà xé thêm": "Zusätzliches zerfetztes Huhn",
      "Đùi gà xối mỡ thêm": "Zusätzliche knusprige Hühnerkeule",
      "Cơm thêm": "Zusätzlicher Reis",
      "Bò xào rau củ thêm": "Zusätzliches Rindfleisch mit Gemüse",
      "Nước ngọt các loại": "Erfrischungsgetränke aller Art",
      "Bò húc": "Red Bull",
      "Nước suối": "Mineralwasser ohne Kohlensäure",
      "Nước khoáng lạt": "Mildes Mineralwasser",
      "Nước dừa trái": "Frische Kokosnuss",
      "Nước cam tươi": "Frischer Orangensaft",
      "Larue": "Larue Bier",
      "Huda": "Huda Bier",
      "Saigon": "Saigon Bier",
      "Tiger": "Tiger Bier",
      "Heineken": "Heineken Bier"
    }
  },

  tw: {
    flag: "🇹🇼",
    total: "總計",
    items: {
      "Cơm sườn + trứng": "烤豬排加煎蛋飯",
      "Cơm gà xé": "雞絲飯",
      "Cơm đùi gà chiên mắm": "魚露炸雞腿飯",
      "Cơm chiên hải sản": "海鮮炒飯",
      "Cơm đùi gà xối mỡ": "脆皮炸雞腿飯",
      "Cơm bò xào rau củ": "牛肉炒時蔬飯",
      "Mỳ xào bò": "牛肉炒麵",
      "Mỳ xào hải sản": "海鮮炒麵",
      "Miến xào bò": "牛肉炒冬粉",
      "Miến xào hải sản": "海鮮炒冬粉",
      "Miến nước gà": "雞肉冬粉湯",
      "Miến nước bò": "牛肉冬粉湯",
      "Miến nước hải sản": "海鮮冬粉湯",
      "Cháo nghêu": "蛤蜊粥",
      "Cháo bò": "牛肉粥",
      "Nghêu hấp": "清蒸蛤蜊",
      "Nghêu xào": "炒蛤蜊",
      "Tôm hấp": "清蒸大蝦",
      "Tôm chiên mắm": "魚露炒大蝦",
      "Mực hấp": "清蒸魷魚",
      "Mực chiên mắm": "魚露炒魷魚",
      "Trứng thêm": "加煎蛋",
      "Canh khổ qua thêm": "加苦瓜湯",
      "Ram chả giò (1 cái)": "炸春捲 (1個)",
      "Sườn nướng thêm": "加烤豬排",
      "Đùi gà chiên mắm thêm": "加魚露雞腿",
      "Phần gà xé thêm": "加雞絲",
      "Đùi gà xối mỡ thêm": "加脆皮雞腿",
      "Cơm thêm": "加飯",
      "Bò xào rau củ thêm": "加牛肉炒時蔬",
      "Nước ngọt các loại": "各式軟飲料",
      "Bò húc": "紅牛",
      "Nước suối": "礦泉水",
      "Nước khoáng lạt": "氣泡水",
      "Nước dừa trái": "新鮮椰子汁",
      "Nước cam tươi": "鮮榨橙汁",
      "Larue": "拉魯啤酒",
      "Huda": "胡達啤酒",
      "Saigon": "西貢啤酒",
      "Tiger": "老虎啤酒",
      "Heineken": "喜力啤酒"
    }
  },

  sg: {
    flag: "🇸🇬",
    total: "TOTAL",
    items: {
      "Cơm sườn + trứng": "Grilled pork chop with egg rice",
      "Cơm gà xé": "Shredded chicken rice",
      "Cơm đùi gà chiên mắm": "Fried chicken thigh with fish sauce rice",
      "Cơm chiên hải sản": "Seafood fried rice",
      "Cơm đùi gà xối mỡ": "Crispy fried chicken thigh rice",
      "Cơm bò xào rau củ": "Stir-fried beef with vegetables rice",
      "Mỳ xào bò": "Stir-fried beef noodles",
      "Mỳ xào hải sản": "Stir-fried seafood noodles",
      "Miến xào bò": "Stir-fried beef glass noodles",
      "Miến xào hải sản": "Stir-fried seafood glass noodles",
      "Miến nước gà": "Chicken glass noodle soup",
      "Miến nước bò": "Beef glass noodle soup",
      "Miến nước hải sản": "Seafood glass noodle soup",
      "Cháo nghêu": "Clam porridge",
      "Cháo bò": "Beef porridge",
      "Nghêu hấp": "Steamed clams",
      "Nghêu xào": "Stir-fried clams",
      "Tôm hấp": "Steamed prawns",
      "Tôm chiên mắm": "Fried prawns with fish sauce",
      "Mực hấp": "Steamed squid",
      "Mực chiên mắm": "Fried squid with fish sauce",
      "Trứng thêm": "Extra egg",
      "Canh khổ qua thêm": "Extra bitter gourd soup",
      "Ram chả giò (1 cái)": "Fried spring roll (1 pc)",
      "Sườn nướng thêm": "Extra grilled pork chop",
      "Đùi gà chiên mắm thêm": "Extra fish sauce chicken thigh",
      "Phần gà xé thêm": "Extra shredded chicken",
      "Đùi gà xối mỡ thêm": "Extra crispy chicken thigh",
      "Cơm thêm": "Extra rice",
      "Bò xào rau củ thêm": "Extra stir-fried beef with vegetables",
      "Nước ngọt các loại": "Assorted soft drinks",
      "Bò húc": "Red Bull",
      "Nước suối": "Bottled water",
      "Nước khoáng lạt": "Mineral water",
      "Nước dừa trái": "Fresh coconut water",
      "Nước cam tươi": "Fresh orange juice",
      "Larue": "Larue Beer",
      "Huda": "Huda Beer",
      "Saigon": "Saigon Beer",
      "Tiger": "Tiger Beer",
      "Heineken": "Heineken Beer"
    }
  },

  id: {
    flag: "🇮🇩",
    total: "TOTAL",
    items: {
      "Cơm sườn + trứng": "Nasi iga babi bakar dengan telur",
      "Cơm gà xé": "Nasi ayam suwir",
      "Cơm đùi gà chiên mắm": "Nasi paha ayam goreng saus ikan",
      "Cơm chiên hải sản": "Nasi goreng seafood",
      "Cơm đùi gà xối mỡ": "Nasi paha ayam goreng ekstra renyah",
      "Cơm bò xào rau củ": "Tumis daging sapi dengan sayuran dan nasi",
      "Mỳ xào bò": "Mie goreng daging sapi",
      "Mỳ xào hải sản": "Mie goreng seafood",
      "Miến xào bò": "Sohun goreng daging sapi",
      "Miến xào hải sản": "Sohun goreng seafood",
      "Miến nước gà": "Sup sohun ayam",
      "Miến nước bò": "Sup sohun daging sapi",
      "Miến nước hải sản": "Sup sohun seafood",
      "Cháo nghêu": "Bubur kerang",
      "Cháo bò": "Bubur daging sapi",
      "Nghêu hấp": "Kerang kukus",
      "Nghêu xào": "Kerang tumis",
      "Tôm hấp": "Udang kukus",
      "Tôm chiên mắm": "Udang goreng saus ikan",
      "Mực hấp": "Cumi-cumi kukus",
      "Mực chiên mắm": "Cumi-cumi goreng saus ikan",
      "Trứng thêm": "Tambahan telur",
      "Canh khổ qua thêm": "Tambahan sup peria / pare",
      "Ram chả giò (1 cái)": "Lumpia goreng (1 biji)",
      "Sườn nướng thêm": "Tambahan iga bakar",
      "Đùi gà chiên mắm thêm": "Tambahan paha ayam saus ikan",
      "Phần gà xé thêm": "Tambahan ayam suwir",
      "Đùi gà xối mỡ thêm": "Tambahan paha ayam renyah",
      "Cơm thêm": "Tambahan nasi",
      "Bò xào rau củ thêm": "Tambahan tumis daging sapi dengan sayuran",
      "Nước ngọt các loại": "Aneka minuman ringan",
      "Bò húc": "Kratingdaeng (Red Bull)",
      "Nước suối": "Air mineral",
      "Nước khoáng lạt": "Air soda tawar",
      "Nước dừa trái": "Air kelapa muda segar",
      "Nước cam tươi": "Jus jeruk segar",
      "Larue": "Bir Larue",
      "Huda": "Bir Huda",
      "Saigon": "Bir Saigon",
      "Tiger": "Bir Tiger",
      "Heineken": "Bir Heineken"
    }
  },

  my: {
    flag: "🇲🇾",
    total: "TOTAL",
    items: {
      "Cơm sườn + trứng": "Nasi rusuk babi bakar dengan telur",
      "Cơm gà xé": "Nasi ayam siat",
      "Cơm đùi gà chiên mắm": "Nasi paha ayam goreng sos ikan",
      "Cơm chiên hải sản": "Nasi goreng makanan laut",
      "Cơm đùi gà xối mỡ": "Nasi paha ayam goreng rangup",
      "Cơm bò xào rau củ": "Daging lembu goreng kilas dengan sayur dan nasi",
      "Mỳ xào bò": "Mee goreng daging lembu",
      "Mỳ xào hải sản": "Mee goreng makanan laut",
      "Miến xào bò": "Suhun goreng daging lembu",
      "Miến xào hải sản": "Suhun goreng makanan laut",
      "Miến nước gà": "Sup suhun ayam",
      "Miến nước bò": "Sup suhun daging lembu",
      "Miến nước hải sản": "Sup suhun makanan laut",
      "Cháo nghêu": "Bubur remis / kupang",
      "Cháo bò": "Bubur daging lembu",
      "Nghêu hấp": "Remis dikukus",
      "Nghêu xào": "Remis digoreng",
      "Tôm hấp": "Udang dikukus",
      "Tôm chiên mắm": "Udang goreng sos ikan",
      "Mực hấp": "Sotong dikukus",
      "Mực chiên mắm": "Sotong goreng sos ikan",
      "Trứng thêm": "Telur tambahan",
      "Canh khổ qua thêm": "Sup peria tambahan",
      "Ram chả giò (1 cái)": "Popia goreng (1 biji)",
      "Sườn nướng thêm": "Rusuk bakar tambahan",
      "Đùi gà chiên mắm thêm": "Paha ayam sos ikan tambahan",
      "Phần gà xé thêm": "Ayam siat tambahan",
      "Đùi gà xối mỡ thêm": "Paha ayam rangup tambahan",
      "Cơm thêm": "Nasi tambahan",
      "Bò xào rau củ thêm": "Tambahan daging lembu goreng kilas dengan sayur",
      "Nước ngọt các loại": "Pelbagai jenis air gas",
      "Bò húc": "Red Bull",
      "Nước suối": "Air mineral",
      "Nước khoáng lạt": "Air soda",
      "Nước dừa trái": "Air kelapa segar",
      "Nước cam tươi": "Jus oren segar",
      "Larue": "Bir Larue",
      "Huda": "Bir Huda",
      "Saigon": "Bir Saigon",
      "Tiger": "Bir Tiger",
      "Heineken": "Bir Heineken"
    }
  },

  in: {
    flag: "🇮🇳",
    total: "TOTAL",
    items: {
      "Cơm sườn + trứng": "ग्रिल्ड पोर्क चॉप्स और अंडा चावल (Rice with Pork & Egg)",
      "Cơm gà xé": "कटे हुए चिकन के साथ चावल (Shredded Chicken Rice)",
      "Cơm đùi gà chiên mắm": "फिश सॉस चिकन ड्रमस्टिक चावल (Fish Sauce Chicken Rice)",
      "Cơm chiên hải sản": "सीफूड फ्राइड राइस (Seafood Fried Rice)",
      "Cơm đùi gà xối mỡ": "क्रिस्पी चिकन थाई चावल (Crispy Chicken Rice)",
      "Cơm bò xào rau củ": "सब्जियों और बीफ के साथ चावल (Stir-fried Beef Rice)",
      "Mỳ xào bò": "बीफ फ्राइड नूडल्स (Beef Fried Noodles)",
      "Mỳ xào hải sản": "सीफूड फ्राइड नूडल्स (Seafood Fried Noodles)",
      "Miến xào bò": "बीफ के साथ फ्राइड ग्लास नूडल्स (Stir-fried Beef Glass Noodles)",
      "Miến xào hải sản": "सीफूड फ्राइड ग्लास नूडल्स (Seafood Glass Noodles)",
      "Miến nước gà": "चिकन ग्लास नूडल सूप (Chicken Glass Noodle Soup)",
      "Miến nước bò": "बीफ ग्लास नूडल सूप (Beef Glass Noodle Soup)",
      "Miến nước hải sản": "सीफूड ग्लास नूडл सूप (Seafood Glass Noodle Soup)",
      "Cháo nghêu": "क्लैम दलिया (Clam Porridge)",
      "Cháo bò": "बीफ दलिया (Beef Porridge)",
      "Nghêu hấp": "उबले हुए क्लैम (Steamed Clams)",
      "Nghêu xào": "तले हुए क्लैम (Stir-fried Clams)",
      "Tôm hấp": "उबले हुए झींगे (Steamed Prawns)",
      "Tôm chiên mắm": "फिश सॉस फ्राइड झींगे (Fried Prawns in Fish Sauce)",
      "Mực hấp": "उबली हुई स्क्विड (Steamed Squid)",
      "Mực chiên mắm": "फिश सॉस फ्राइड स्क्विड (Fried Squid in Fish Sauce)",
      "Trứng thêm": "अतिरिक्त अंडा (Extra Egg)",
      "Canh khổ qua thêm": "करेला सूप (Extra Bitter Melon Soup)",
      "Ram chả giò (1 cái)": "फ्राइड स्प्रिंग रोल (Spring Roll - 1 Pc)",
      "Sườn nướng thêm": "अतिरिक्त ग्रिल्ड रिब्स (Extra Grilled Ribs)",
      "Đùi gà chiên mắm thêm": "अतिरिक्त फिश सॉस चिकन (Extra Fish Sauce Chicken)",
      "Phần gà xé thêm": "अतिरिक्त चिकन श्रेड (Extra Shredded Chicken)",
      "Đùi gà xối mỡ thêm": "अतिरिक्त क्रिस्पी चिकन (Extra Crispy Chicken)",
      "Cơm thêm": "अतिरिक्त चावल (Extra Rice)",
      "Bò xào rau củ thêm": "अतिरिक्त बीफ़ सब्जी (Extra Stir-fried Beef)",
      "Nước ngọt các loại": "कोल्ड ड्रिंक्स (Assorted Soft Drinks)",
      "Bò húc": "रेड बुल (Red Bull)",
      "Nước suối": "पानी की बोतल (Mineral Water)",
      "Nước khoáng lạt": "सोडा वाटर (Sparkling Water)",
      "Nước dừa trái": "नारियल पानी (Fresh Coconut Water)",
      "Nước cam tươi": "संतरे का रस (Fresh Orange Juice)",
      "Larue": "लारू बियर (Larue Beer)",
      "Huda": "हुडा बियर (Huda Beer)",
      "Saigon": "साइगॉन बियर (Saigon Beer)",
      "Tiger": "टाइगर बियर (Tiger Beer)",
      "Heineken": "हैनेकेन बियर (Heineken Beer)"
    }
  },

  fi: {
    flag: "🇫🇮",
    total: "YHTEENSÄ",
    items: {
      "Cơm sườn + trứng": "Riisiä, grillattua porsaankylkeä ja kananmuna",
      "Cơm gà xé": "Riisiä ja revittyä kanaa",
      "Cơm đùi gà chiên mắm": "Riisiä ja kanankoipi kalakastikkeessa",
      "Cơm chiên hải sản": "Paistettua riisiä merenelävilla",
      "Cơm đùi gà xối mỡ": "Riisiä ja erittäin rapeaa kanankoipea",
      "Cơm bò xào rau củ": "Paistettua nautaa ja vihanneksia riisillä",
      "Mỳ xào bò": "Paistettuja nuudeleita ja nautaa",
      "Mỳ xào hải sản": "Paistettuja nuudeleita ja mereneläviä",
      "Miến xào bò": "Paistettua lasinuudelia ja nautaa",
      "Miến xào hải sản": "Paistettua lasinuudelia ja mereneläviä",
      "Miến nước gà": "Lasinuudelikeitto kanalla",
      "Miến nước bò": "Lasinuudelikeitto naudalla",
      "Miến nước hải sản": "Lasinuudelikeitto merenelävillä",
      "Cháo nghêu": "Simpukkariisipuuro",
      "Cháo bò": "Naudanlihariisipuuro",
      "Nghêu hấp": "Höyrytetyt simpukat",
      "Nghêu xào": "Paistetut simpukat",
      "Tôm hấp": "Höyrytetyt ravut",
      "Tôm chiên mắm": "Paistetut ravut kalakastikkeessa",
      "Mực hấp": "Höyrytetty mustekala",
      "Mực chiên mắm": "Paistettu mustekala kalakastikkeessa",
      "Trứng thêm": "Ylimääräinen kananmuna",
      "Canh khổ qua thêm": "Ylimääräinen karvaskurkkukeitto",
      "Ram chả giò (1 cái)": "Kevätkääryle (1 kpl)",
      "Sườn nướng thêm": "Ylimääräinen grillattu kylki",
      "Đùi gà chiên mắm thêm": "Ylimääräinen kanankoipi kalakastikkeessa",
      "Phần gà xé thêm": "Ylimääräinen revitty kana",
      "Đùi gà xối mỡ thêm": "Ylimääräinen rapea kanankoipi",
      "Cơm thêm": "Lisäriisi",
      "Bò xào rau củ thêm": "Ylimääräinen paistettu nauta vihanneksilla",
      "Nước ngọt các loại": "Virvoitusjuomat laidasta laitaan",
      "Bò húc": "Red Bull",
      "Nước suối": "Lähdevesi",
      "Nước khoáng lạt": "Kivennäisvesi",
      "Nước dừa trái": "Tuore kookosvesi",
      "Nước cam tươi": "Tuore appelsiinimehu",
      "Larue": "Larue-olut",
      "Huda": "Huda-olut",
      "Saigon": "Saigon-olut",
      "Tiger": "Tiger-olut",
      "Heineken": "Heineken-olut"
    }
  },

  nl: {
    flag: "🇳🇱",
    total: "TOTAAL",
    items: {
      "Cơm sườn + trứng": "Rijst met gegrilde varkenskrabbetjes en ei",
      "Cơm gà xé": "Rijst met geplukte kip",
      "Cơm đùi gà chiên mắm": "Rijst met kippenbout in vissaus",
      "Cơm chiên hải sản": "Gebakken rijst met zeevruchten",
      "Cơm đùi gà xối mỡ": "Rijst met superkrokante kippenbout",
      "Cơm bò xào rau củ": "Roergebakken rundvlees met groenten en rijst",
      "Mỳ xào bò": "Gebakken mie met rundvlees",
      "Mỳ xào hải sản": "Gebakken mie met zeevruchten",
      "Miến xào bò": "Gebakken glasnoedels met rundvlees",
      "Miến xào hải sản": "Gebakken glasnoedels met zeevruchten",
      "Miến nước gà": "Glasnoedelsoep met kip",
      "Miến nước bò": "Glasnoedelsoep met rundvlees",
      "Miến nước hải sản": "Glasnoedelsoep met zeevruchten",
      "Cháo nghêu": "Rijstcongee met kokkels",
      "Cháo bò": "Rijstcongee met rundvlees",
      "Nghêu hấp": "Gestoomde kokkels",
      "Nghêu xào": "Roergebakken kokkels",
      "Tôm hấp": "Gestoomde garnalen",
      "Tôm chiên mắm": "Gebakken garnalen in vissaus",
      "Mực hấp": "Gestoomde inktvis",
      "Mực chiên mắm": "Gebakken inktvis in vissaus",
      "Trứng thêm": "Extra ei",
      "Canh khổ qua thêm": "Extra bitterkomkommersoep",
      "Ram chả giò (1 cái)": "Kwaliteitsloempia (1 stuk)",
      "Sườn nướng thêm": "Extra gegrilde sparerib",
      "Đùi gà chiên mắm thêm": "Extra kippenbout in vissaus",
      "Phần gà xé thêm": "Extra geplukte kip",
      "Đùi gà xối mỡ thêm": "Extra krokante kippenbout",
      "Cơm thêm": "Extra rijst",
      "Bò xào rau củ thêm": "Extra roergebakken rundvlees met groenten",
      "Nước ngọt các loại": "Frisdranken naar keuze",
      "Bò húc": "Red Bull",
      "Nước suối": "Stil water",
      "Nước khoáng lạt": "Bruiswater / Mineraalwater",
      "Nước dừa trái": "Vers kokoswater",
      "Nước cam tươi": "Vers geperst sinaasappelsap",
      "Larue": "Larue bier",
      "Huda": "Huda bier",
      "Saigon": "Saigon bier",
      "Tiger": "Tiger bier",
      "Heineken": "Heineken bier"
    }
  },

  se: {
    flag: "🇸🇪",
    total: "TOTALT",
    items: {
      "Cơm sườn + trứng": "Ris med grillade fläskkotletter och ägg",
      "Cơm gà xé": "Ris med strimlad kyckling",
      "Cơm đùi gà chiên mắm": "Ris med kycklingklubba i fisksås",
      "Cơm chiên hải sản": "Stekt ris med skaldjur",
      "Cơm đùi gà xối mỡ": "Ris med extra krispig kycklingklubba",
      "Cơm bò xào rau củ": "Wokat nötkött med grönsaker och ris",
      "Mỳ xào bò": "Stekta nudlar med nötkött",
      "Mỳ xào hải sản": "Stekta nudlar med skaldjur",
      "Miến xào bò": "Stekta glasnudlar med nötkött",
      "Miến xào hải sản": "Stekta glasnudlar med skaldjur",
      "Miến nước gà": "Glasnudelsoppa med kyckling",
      "Miến nước bò": "Glasnudelsoppa med nötkött",
      "Miến nước hải sản": "Glasnudelsoppa med skaldjur",
      "Cháo nghêu": "Risgröt med musslor",
      "Cháo bò": "Risgröt med nötkött",
      "Nghêu hấp": "Ångkokta musslor",
      "Nghêu xào": "Wokade musslor",
      "Tôm hấp": "Ångkokta räkor",
      "Tôm chiên mắm": "Stekta räkor i fisksås",
      "Mực hấp": "Ångkokt bläckfisk",
      "Mực chiên mắm": "Stekt bläckfisk i fisksås",
      "Trứng thêm": "Extra ägg",
      "Canh khổ qua thêm": "Extra bittermelonnyponsoppa",
      "Ram chả giò (1 cái)": "Vårrulle (1 st)",
      "Sườn nướng thêm": "Extra grillad kotlett",
      "Đùi gà chiên mắm thêm": "Extra kycklingklubba i fisksås",
      "Phần gà xé thêm": "Extra strimlad kyckling",
      "Đùi gà xối mỡ thêm": "Extra krispig kycklingklubba",
      "Cơm thêm": "Extra ris",
      "Bò xào rau củ thêm": "Extra wokat nötkött med grönsaker",
      "Nước ngọt các loại": "Läskedrycker av alla slag",
      "Bò húc": "Red Bull",
      "Nước suối": "Källvatten",
      "Nước khoáng lạt": "Lätt kolsyrat mineralvatten",
      "Nước dừa trái": "Färskt kokosvatten",
      "Nước cam tươi": "Färskpressad apelsinjuice",
      "Larue": "Larue öl",
      "Huda": "Huda öl",
      "Saigon": "Saigon öl",
      "Tiger": "Tiger öl",
      "Heineken": "Heineken öl"
    }
  },

  ch: {
    flag: "🇨🇭",
    total: "GESAMT",
    items: {
      "Cơm sườn + trứng": "Reis mit gegrillten Schweinsrippli und Ei",
      "Cơm gà xé": "Reis mit gezupftem Poulet",
      "Cơm đùi gà chiên mắm": "Reis mit Pouletschenkel in Fischsauce",
      "Cơm chiên hải sản": "Gebratener Reis mit Meeresfrüchten",
      "Cơm đùi gà xối mỡ": "Reis mit knusprigem Pouletschenkel",
      "Cơm bò xào rau củ": "Gebratenes Rindfleisch mit Gemüse und Reis",
      "Mỳ xào bò": "Gebratene Nudeln mit Rindfleisch",
      "Mỳ xào hải sản": "Gebratene Nudeln mit Meeresfrüchten",
      "Miến xào bò": "Gebratene Glasnudeln mit Rindfleisch",
      "Miến xào hải sản": "Gebratene Glasnudeln mit Meeresfrüchten",
      "Miến nước gà": "Glasnudelsuppe mit Poulet",
      "Miến nước bò": "Glasnudelsuppe mit Rindfleisch",
      "Miến nước hải sản": "Glasnudelsuppe mit Meeresfrüchten",
      "Cháo nghêu": "Reisbrei (Congee) mit Muscheln",
      "Cháo bò": "Reisbrei (Congee) mit Rindfleisch",
      "Nghêu hấp": "Gedämpfte Muscheln",
      "Nghêu xào": "Gebratene Muscheln",
      "Tôm hấp": "Gedämpfte Riesencrevetten",
      "Tôm chiên mắm": "Gebratene Riesencrevetten in Fischsauce",
      "Mực hấp": "Gedämpfter Tintenfisch",
      "Mực chiên mắm": "Gebratenes Tintenfisch in Fischsauce",
      "Trứng thêm": "Extra Ei",
      "Canh khổ qua thêm": "Extra Bittermelonen-Suppe",
      "Ram chả giò (1 cái)": "Frühlingsrolle (1 Stk.)",
      "Sườn nướng thêm": "Extra gegrilltes Rippli",
      "Đùi gà chiên mắm thêm": "Extra Pouletschenkel in Fischsauce",
      "Phần gà xé thêm": "Extra gezupftes Poulet",
      "Đùi gà xối mỡ thêm": "Extra knuspriges Pouletschenkel",
      "Cơm thêm": "Extra Reis",
      "Bò xào rau củ thêm": "Extra gebratenes Rindfleisch mit Gemüse und Reis",
      "Nước ngọt các loại": "Softdrinks aller Art",
      "Bò húc": "Red Bull",
      "Nước suối": "Mineralwasser ohne Kohlensäure",
      "Nước khoáng lạt": "Stilles Mineralwasser",
      "Nước dừa trái": "Frisches Kokoswasser",
      "Nước cam tươi": "Frischer Orangensaft",
      "Larue": "Larue Bier",
      "Huda": "Huda Bier",
      "Saigon": "Saigon Bier",
      "Tiger": "Tiger Bier",
      "Heineken": "Heineken Bier"
    }
  }
};
